### ISSUE TITLE
Monero version on Tor not working as intended

### ISSUE THREAD

**Issue by ChiefGyk3D** [monero-ecosystem/PiNode-XMR#27]
It binds to the local IP but the issue is since the script isn't wrapped to use tor socks it looks like it won't allow the connection. I had to bind it locally to a device IP, like a normal private nod. My Monero GUI could not only connect now, but with a modification of the scripts the version and block sync status displayed.
Furthermore I may be wrong but it looks like P2P syncing is also done over Tor with the current configuration and should be bound locally unless I am mistaken and keeping the tx flag as is presently configured.

**Comment by viperperidot** [comment]
As a side note to this my webui is only displaying the last 2 digits of the monero version for some reason.

So .1.1 instead of 0.17.1.1

![image](https://user-images.githubusercontent.com/70721357/97621275-5723c080-19e8-11eb-8797-37bfb990a38a.png)

**Comment by shermand100** [comment]
@viperperidot 
This is a known inconvenience and will be fixed very soon.
It is a result of Monero outputting it's version when called with prep-ending ANSI colour codes. When the version script is called I have piped it through` | cut -c 5-`  to remove the ANSI colour code that would otherwise be displayed as something like `[0;34m0.17.1.1-release`

It was an attempt to tidy up the displayed result, it worked on previous versions but in this case has hasn't had the desired result.

If you need to double check the Monero version is also printed at the bottom of the block explorer home page too.

**Comment by shermand100** [comment]
@ChiefGyk I think I need a bit more clarification on this. What are trying to do, how do you expect it to behave, what are you experiencing that differs from that?
There may be some optimising needed here as Monero Anonymity network documentation I think really is bad. I spend many hours tweaking this configuration.
I believe currently it sync's over P2P clearnet, makes tor connections, transactions from local connections that are not in the tx pool are only broadcast to the tor network. RPC wallet connections are available via tor hostname.onion:18080 RPCuser:RPCpass for wallet sync and tx broadcast.
