### ISSUE TITLE
Tor onion address not displaying on webui even though Tor is running

### ISSUE THREAD

**Issue by viperperidot** [monero-ecosystem/PiNode-XMR#28]
On the Node Control page of the WebUI under TOR, the public address or Onion URL is not displaying even though I have Tor installed and running. Instead a message is displayed saying -- Data Will be generated on boot --. I was able to fix this issue in the previous PiNode version by re-installing Tor. However, I tried this method and it does not seem to resolve the issue on the current version of PiNodeXMR. See below for image reference.

![image](https://user-images.githubusercontent.com/70721357/97620544-58082280-19e7-11eb-9bd3-67bee19f3d06.png)

**Comment by shermand100** [comment]
Are you able to delete the web page cache to refresh that box?

That box used to be a box of imported text that was easy to refresh.
Since I've made things a little prettier the cache seems more persistent despite efforts to prevent caching.

The command to produce that hostname is run in the tor installer script. If you've run it twice I'd be very surprised if your hostname wasn't generated. However if it still isn't being displayed the command to populate that text box is:

`sudo cat /var/lib/tor/hidden_service/hostname > /var/www/html/onion-address.txt`

or to display it in the command line for your records:

`sudo cat /var/lib/tor/hidden_service/hostname`

**Comment by shermand100** [comment]
For future development this issue can be closed on the completion of the following 2 conditions:

1)
`sudo cat /var/lib/tor/hidden_service/hostname > /var/www/html/onion-address.txt` is added to the script to start the tor node, as there is no handicap to running this command multiple times. The hidden service keys are generated and stoed on tor install and are unique to each PiNodeXMR device. The hidden service address won't change. Running this command on each tor PiNodeXMR start call should ensure the population of this field.

2)
Make changes to better disable caching of page data for PiNodeXMR pages. This will prevent old status messages from being displayed and fresh/new/current data displaying correctly as intended.

**Comment by viperperidot** [comment]
I cleared my browser cache and that worked thanks!

**Comment by shermand100** [comment]
Both proposed fixes implemented.  Caching has been disabled on PiNodeXMR.
https://github.com/monero-ecosystem/PiNode-XMR/commit/d0acc97d706e28efa58a7b89688dc5113ff18504
