### ISSUE TITLE
Disable swap button not working

### ISSUE THREAD

**Issue by viperperidot** [monero-ecosystem/PiNode-XMR#31]
I am trying to disable swap using the web GUI but when I click the button it says that swap has been disabled however it still shows swap being used on the web UI under Memory.

**Comment by shermand100** [comment]
Somehow a permissions issue snuck in. Command needs to be run as root/sudo privileges.

Fixed with:

#https://github.com/monero-ecosystem/PiNode-XMR/commit/d0787454ce6d6eaaa105747ebd9413a30710db75 Armbian Branch

#https://github.com/monero-ecosystem/PiNode-XMR/commit/bdeda1c30b5efe9ec2474a8017a171151573a4d7 Raspbian Branch
