### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by dkroen17** [monero-ecosystem/PiNode-XMR#47]
I ran:

wget -O   -   https://raw.githubusercontent.com/monero-ecosystem/PiNode-XMR/master/Install-PiNode-XMR.sh   \| bash
--

</body>

</html>

I got:
022-01-04 05:02:03 (5.37 MB/s) - ‘raspbian.sh’ saved [2954/2954]

PiNode-XMR Raspbian configuration file received
Starting Installation
chmod: cannot access '/home/pi/raspbian.sh': No such file or directory
bash: line 26: ./raspbian.sh: Permission denied

**Comment by shermand100** [comment]
Hi, sorry for the slow reply.

That would be a response encountered if you either weren't running the command as user 'pi' which is essential.
Or it could be that the file failed to download, but I assume you tried the command more than once?

**Comment by shermand100** [comment]
Hi there do you need further help? Did you resolve this?

**Comment by shermand100** [comment]
Nothing heard, but happy to re-open if needed.

Issue most likely a permission issue which has since been resolved otherwise I suspect this issue would be more prevalent.
I also note that the script the user tried to run is the now obsolete 'Raspbian' Branch for Raspberry Pi OS. Future users are advised to use the Ubuntu Branch (available for RPi via the standard 'Raspberry Pi Imager' Software under "Other OS" for best performance, security and features.

Closing
