### ISSUE TITLE
License

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/PiNode-XMR#6]
@shermand100 this repository doesn't provide any license, Is that on purpose? If it's not, i strongly suggest to add one.

**Comment by shermand100** [comment]
Hi, that isn't on purpose but since I saw this 2 days ago I've been looking at some options.

I have no interest in monetising this project as I think privacy and Monero should be free and open to all.
To that end I'm considering a GNU license or to use/adapt the one from the Monero project GitHub.

Sorry for not seeing this issue raised, I'm currently in Africa for work and have very limited internet.

**Comment by erciccione** [comment]
I see you went for the GPL-3 at the end. Thanks! :)
