### ISSUE TITLE
Compiling on Ubuntu 22.04 on RPi3B+

### ISSUE THREAD

**Issue by dawiepoolman** [monero-ecosystem/PiNode-XMR#74]
anyone managed to do this?  I get LOTS of errors.

**Comment by shermand100** [comment]
Ok, doing a test build now. I'll see what the result is tomorrow morning.

**Comment by dawiepoolman** [comment]
hi @shermand100 
I tried to do a full forced upgrade last night as well and it completed but the binary dir has nothing in it:
~/monero/build/release/bin$

**Comment by dawiepoolman** [comment]
oh, and I boot from SSD and running 64bit Ubuntu

**Comment by shermand100** [comment]
So my Pi3 install failed last night but only because my laptop did a windows update and restarted whilst I was sleeping.
I set it going again this evening and the Pi3 has successfully built monero however this was using the Ubuntu 32bit 22.04 server LTS.
I'll do another build on the 64bit OS to see if that is it's downfall.

Personally due to the Pi processor not being able to use the BlockExplorer I would suggest using a Pi3B+ with PiNodeXMR Light Mode.
It will get the Monero Armv7 binaries instead of building from source which will be much faster. (No Blockexplorer or P2Pool though) All Node features are included.

**Comment by dawiepoolman** [comment]
awesome thx shermand100
ok, I will flush and re-try with 32bit.  will be interesting to see if your node manages to compile the 64bit

**Comment by shermand100** [comment]
@dawiepoolman 
Yes bud. Sorry for the delay but from the Raspbery Pi disk imager, other OS's you'll need the Ubuntu Server 32bit 22.04 LTS.

A while back I think I understood general complaints on how the Pi3 wasn't actually 64bit, I don't remember now but in our use case it affects how the Pi processor can't perform some of the crypto extensions needed.

I'll amend our Hardware wiki to explicitly specify the 32bit ubuntu for Pi3 devices.
Thanks for highlighting this.

Has this got you installed now?

**Comment by dawiepoolman** [comment]
hi @shermand100 
I got the 32bit Ubuntu version working last night - thank you.  It compiled and I am running the blockchain sync now.
We can close this.  Thanks again!
